[project]
name = "vardef-maintenance"
version = "0.1.0"
description = "Dependencies necessary to run Notebooks for maintenance of variable definitions at Statistics Norway."
requires-python = "^3.10"                                                                                             # This should match the range in dapla-toolbelt-metadata
dependencies = ["dapla-toolbelt-metadata>=0.10.1", "ipykernel"]

[tool.poetry]
package-mode = false # We don't want to install this "project", just the dependencies

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
